# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39334ab938d2df583f93e20ad3ec9d82ba1d768d3364d5d35dbe72508245ad7c88d5da5192b39afe376a02eceb0dfcce3f484167a95b9c68ff4b752d04b01d9b

test:
  secret_key_base: 0ceebe2532d630a93aebdf095628f83a52de12f5434d190823e054b27c224feae2ce570acefeeca87e28413d9d485582dffe5ea8e1e0e85fab902d7c380ac708

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
